functionsDirectory = "C:\\Users\\tscr\\Downloads\\quantumnexus-ai-main\\quantumnexus-ai-main\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []

[build]
publish = "C:\\Users\\tscr\\Downloads\\quantumnexus-ai-main\\quantumnexus-ai-main\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "hugo"
functions = "C:\\Users\\tscr\\Downloads\\quantumnexus-ai-main\\quantumnexus-ai-main\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]