// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwuuqgdpdybyfpcjzzbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53dXVxZ2RwZHlieWZwY2p6emJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTQxNzYsImV4cCI6MjA3MTE5MDE3Nn0.ykqzUijwe82IUgOPnCyy44huW4_1nJdfeJJfrTui-kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});